# Generated by Django 2.2.1 on 2019-05-07 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.BooleanField()),
                ('age', models.IntegerField()),
                ('nickname', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('genre', models.CharField(max_length=256)),
                ('description', models.CharField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eget consequat eros, a lacinia turpis. Phasellus faucibus commodo diam', max_length=256, null=True)),
                ('rate', models.FloatField(default=0.0)),
                ('votes', models.IntegerField(default=0)),
                ('running_time', models.IntegerField(default=0)),
                ('director', models.CharField(max_length=256)),
                ('actor', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(default=0.0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Customer')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Movie')),
            ],
        ),
    ]
